Repository ublue-os/bluefin-docs, pull requests merged in 2025-08, with the labels that each got.

#290 Update index.md
  docs/index.md
Labels: documentation, size:XS

#299 docs: minor typo fix
  docs/press-kit.md
Labels: documentation, lgtm, size:XS

#301 Update installation.md
  docs/installation.md
Labels: documentation, size:XS

#302 Fix: A few grammatical tweaks
  blog/2025-08-08-bluefin-on-lfx.md
Labels: documentation, lgtm, size:S

#327 Replace bluefin-lts-bot author image with vector version
  changelogs/authors.yaml
  static/img/bluefin-lts-release-bot.png
  static/img/bluefin-lts-release-bot.svg
  static/img/logo.svg
Labels: lgtm, size:XS

#328 Replace raster logo with screaming bluefin vector art
  docusaurus.config.ts
  static/img/logo.png
Labels: documentation, size:XS

#329 Replace favicon with the new logo for consistency
  docusaurus.config.ts
  static/img/favicon.ico
Labels: documentation, lgtm, size:XS

#335 Update tagline and blog description for clarity
  docusaurus.config.ts
Labels: documentation, size:XS
