Repository ublue-os/bluefin-docs, pull requests merged in 2025-04, with the labels that each got.

#130 fix: remove stray parentheses
  docs/index.md
Labels: documentation, lgtm, size:XS

#132 docs: Update lts.md
  docs/lts.md
Labels: documentation, lgtm, size:XS

#133 Update analytics.md
  docs/analytics.md
Labels: size:S

#134 Update for F42
  docs/administration.md
Labels: documentation, size:XS

#136 split out cli section
  docs/administration.md
  docs/bluefin-dx.md
  docs/command-line.md
  sidebars.ts
Labels: size:L

#140 typo: remove leftover backticks
  docs/contributing.md
Labels: documentation, lgtm, size:XS

#141 typo: FAQs.md
  docs/FAQ.md
Labels: documentation, lgtm, size:XS

#143 fix: set rolling release for PDFs
  .github/workflows/pdf.yml
Labels: lgtm, size:XS

#144 ci(pdf): checkout git repo for gh cli
  .github/workflows/pdf.yml
Labels: github_actions, lgtm, size:XS

#145 fix: perms for pdfs workflow
  .github/workflows/pdf.yml
Labels: size:XS

#147 docs: add gaming page
  docs/gaming.md
  sidebars.ts
Labels: size:M

#149 revert: revert all the thingies until 5ba5cda
  docs/donations.md
  docs/gaming.md
  sidebars.ts
Labels: documentation, size:M

#150 chore: make sidebar more fitting to project status
  sidebars.ts
Labels: size:S

#152 Adding information about each gaming app and runtimes
  docs/gaming.md
Labels: documentation, lgtm, size:M

#153 fix(ai): alpaca no longer includes ollama
  docs/ai.md
Labels: documentation, lgtm, size:XS

#158 docs(Installation.md): remove typo
  docs/installation.md
Labels: documentation, lgtm, size:XS
