Repository ublue-os/bluefin-docs, pull requests merged in 2025-09, with the labels that each got.

#352 fix: removed redundant local section
  docs/contributing.md
Labels: documentation, size:M

#353 lts.md: CentOS -> CentOS Stream
  docs/lts.md
Labels: documentation, lgtm, size:XS

#354 feat: respect `prefers-color-scheme`
  docusaurus.config.ts
Labels: enhancement, lgtm, size:XS

#356 style: alter link color to match bluefin website
  src/css/custom.css
Labels: lgtm, size:XS

#365 Delete docs/release-sync-setup.md
  docs/release-sync-setup.md
Labels: documentation, size:L

#373 revert: move back to old changelog syncer
  .github/workflows/sync-bluefin-releases.yml
Labels: size:XL

#388 Resize fonts to be more accessible
  src/components/FeedItems.module.css
  src/components/PackageSummary.tsx
Labels: enhancement, lgtm, size:S

#408 chore: fix styling and format of changelog cards
  src/components/FeedItems.module.css
  src/components/FeedItems.tsx
Labels: lgtm, size:M

#418 Add 'Color with Bluefin' PDF announcement
  blog/2025-09-17-color-with-bluefin.md
Labels: documentation, size:S

#395 Create 2025-09-18-bluefin-lts-and-gdx.md
  blog/2025-09-18-bluefin-lts-and-gdx.md
Labels: documentation, size:L

#421 Remove duplicate sentence
  docs/administration.md
Labels: documentation, lgtm, size:XS
