Repository ublue-os/bluefin-docs, pull requests merged in 2025-05, with the labels that each got.

#159 feat: add download page
  docs/downloads.md
  sidebars.ts
Labels: size:M

#160 fix: move arm
  docs/downloads.md
  docs/lts.md
Labels: size:S

#173 Update downloads.md
  docs/downloads.md
Labels: size:XS

#174 Add FAQ regarding language switch key
  docs/FAQ.md
Labels: documentation, lgtm, size:S

#177 docs: fix broken link to secure-boot
  docs/installation.md
Labels: documentation, lgtm, size:XS

#178 Replace me with some new blood in the donation doc
  docs/donations.md
Labels: documentation, lgtm, size:XS

#184 Revert "fix(deps): update docusaurus monorepo to v3.8.0"
  bun.lockb
  package-lock.json
  package.json
Labels: size:S
